// Generated by CoffeeScript 1.3.3
var Square,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Load.CanvasBoxElement();

Square = (function(_super) {

  __extends(Square, _super);

  Square.prototype.side = 100;

  Square.prototype.colorRegular = "rgb(150,150,250)";

  Square.prototype.colorOver = "yellow";

  Square.prototype.colorDrag = "rgb(100,100,250)";

  Square.prototype.color = null;

  Square.prototype.borderColorRegular = "rgb(100,100,100)";

  Square.prototype.borderColor = null;

  Square.prototype.borderColorOver = "rgb( 250 , 250, 250 )";

  Square.prototype.borderWidth = 2;

  Square.prototype.strClassName = "Square";

  Square.prototype.intLastX = 0;

  Square.prototype.intLastY = 0;

  function Square() {
    this.color = this.colorRegular;
    this.borderColor = this.borderColorRegular;
    return Square.__super__.constructor.call(this);
  }

  Square.prototype.toSerialize = function() {
    var objResult;
    objResult = Square.__super__.toSerialize.apply(this, arguments);
    objResult.color = this.color;
    objResult.borderColor = this.borderColor;
    objResult.side = this.side;
    return objResult;
  };

  /*
      # Draw the Square
      # @return Square me
  */


  Square.prototype.draw = function() {
    this.refresh();
    this.objBox.setFillStyle(this.color);
    this.objBox.fillRect(Math.round(this.x - (this.side / 2)), Math.round(this.y - (this.side / 2)), Math.round(this.side), Math.round(this.side));
    this.objBox.setStrokeStyle(this.borderColor);
    this.objBox.lineWidth = "" + this.borderWidth + "px";
    this.objBox.strokeRect(Math.round(this.x - (this.side / 2)), Math.round(this.y - (this.side / 2)), Math.round(this.side), Math.round(this.side));
    this.objBox.setStrokeStyle("black");
    this.objBox.strokeText("Drag and Drop", this.x - 30, this.y);
    return this;
  };

  Square.prototype.onMouseOver = function(event) {
    console.log("square over");
    this.borderColor = this.borderColorOver;
    this.color = this.colorOver;
    return Square.__super__.onMouseOver.call(this, event);
  };

  Square.prototype.onMouseOut = function(event) {
    this.borderColor = this.borderColorRegular;
    this.color = this.colorRegular;
    return Square.__super__.onMouseOut.call(this, event);
  };

  Square.prototype.checkValidPosition = function() {
    if (this.inCollision()) {
      this.x = this.lastValidX;
      return this.y = this.lastValidY;
    } else {
      this.lastValidX = this.x;
      return this.lastValidY = this.y;
    }
  };

  Square.prototype.onDrag = function(event) {
    this.color = this.colorDrag;
    Square.__super__.onDrag.call(this, event);
    this.checkValidPosition();
    return this;
  };

  Square.prototype.goLeft = function(event) {
    Square.__super__.goLeft.call(this, event);
    this.checkValidPosition();
    return this;
  };

  Square.prototype.goRight = function(event) {
    Square.__super__.goRight.call(this, event);
    this.checkValidPosition();
    return this;
  };

  Square.prototype.goUp = function(event) {
    Square.__super__.goUp.call(this, event);
    this.checkValidPosition();
    return this;
  };

  Square.prototype.goDown = function(event) {
    Square.__super__.goDown.call(this, event);
    this.checkValidPosition();
    return this;
  };

  Square.prototype.onDrop = function(event) {
    this.color = this.colorRegular;
    return Square.__super__.onDrop.call(this, event);
  };

  Square.prototype.onClick = function(event) {
    if (this.side < 200) {
      this.side += 5;
    }
    this.onMouseOver(event);
    return Square.__super__.onClick.call(this, event);
  };

  Square.prototype.onDblClick = function(event) {
    this.side = 100;
    return Square.__super__.onDblClick.call(this, event);
  };

  Square.prototype.isInsideElement = function(outX, outY) {
    return (Math.round(outX) >= Math.round(this.x - this.side / 2)) && (Math.round(outX) <= Math.round(this.x + this.side / 2)) && (Math.round(outY) >= Math.round(this.y - this.side / 2)) && (Math.round(outY) <= Math.round(this.y + this.side / 2));
  };

  Square.prototype.inCollision = function() {
    var objElement, _i, _len, _ref;
    _ref = this.objBox.arrElements;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      objElement = _ref[_i];
      if (objElement.getId() !== this.getId()) {
        if (objElement.isInsideElement(this.x - this.side / 2, this.y - this.side / 2) || objElement.isInsideElement(this.x + this.side / 2, this.y - this.side / 2) || objElement.isInsideElement(this.x - this.side / 2, this.y + this.side / 2) || objElement.isInsideElement(this.x + this.side / 2, this.y + this.side / 2) || objElement.isInsideElement(this.x - this.side / 2, this.y) || objElement.isInsideElement(this.x + this.side / 2, this.y) || objElement.isInsideElement(this.x, this.y + this.side / 2) || objElement.isInsideElement(this.x, this.y - this.side / 2)) {
          return true;
        }
      }
    }
    return false;
  };

  return Square;

})(CanvasBoxElement);
