// Generated by CoffeeScript 1.3.3
var Bubble,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Load.CanvasBoxElement();

Bubble = (function(_super) {

  __extends(Bubble, _super);

  function Bubble() {
    return Bubble.__super__.constructor.apply(this, arguments);
  }

  Bubble.prototype.x = 0;

  Bubble.prototype.y = 0;

  Bubble.prototype.side = 1;

  Bubble.prototype.colorRegular = "rgba(250,250,250,0.60)";

  Bubble.prototype.color = "rgba(250,250,250,0.60)";

  Bubble.prototype.colorOver = "orange";

  Bubble.prototype.borderColorRegular = "rgb(100,100,100)";

  Bubble.prototype.borderColor = "rgb(100,100,100)";

  Bubble.prototype.borderColorOver = "rgb( 250 , 250, 250 )";

  Bubble.prototype.borderWidth = 2;

  Bubble.prototype.strClassName = "Bubble";

  Bubble.prototype.objCollision = null;

  /*
      # Is Mouse Over Flag
  */


  Bubble.prototype.isOver = false;

  Bubble.prototype.init = function() {
    Bubble.__super__.init.call(this);
    this.color = this.colorRegular;
    return this.borderColor = this.borderColorRegular;
  };

  Bubble.prototype.draw = function() {
    this.objBox.setStrokeStyle(this.borderColor);
    this.objBox.setFillStyle(this.color);
    this.objBox.setLineWidth(10);
    this.objBox.setStrokeStyle(this.borderColor);
    this.objBox.beginPath();
    this.objBox.arc(this.x, this.y, this.side, 0, Math.PI * 2, true);
    this.objBox.fill();
    this.objBox.stroke();
    return this.objBox.closePath();
  };

  Bubble.prototype.toSerialize = function() {
    var objResult;
    objResult = Bubble.__super__.toSerialize.call(this);
    objResult.color = this.color;
    objResult.borderColor = this.borderColor;
    objResult.side = this.side;
    return objResult;
  };

  Bubble.prototype.onMouseOver = function(event) {
    this.borderColor = this.borderColorOver;
    this.color = this.colorOver;
    this.isOver = true;
    return false;
  };

  Bubble.prototype.onMouseOut = function(event) {
    this.borderColor = this.borderColorRegular;
    this.color = this.colorRegular;
    this.isOver = false;
    return false;
  };

  Bubble.prototype.onDrag = function(event) {
    this.onMouseOver(event);
    return false;
  };

  Bubble.prototype.onDrop = function(event) {
    this.onMouseOut(event);
    return false;
  };

  Bubble.prototype.onClick = function(event) {
    this.killMe();
    return false;
  };

  Bubble.prototype.onTimer = function(event) {
    if (this.isOver) {
      return false;
    }
    this.y -= 2;
    this.side++;
    this.objBox.change();
    if (this.x < (-1 * this.side)) {
      this.killMe();
      return false;
    }
    if (this.y < (-1 * this.side)) {
      this.killMe();
      return false;
    }
    if (this.inCollision()) {
      if (this.y >= this.objCollision.y) {
        this.side--;
        this.y += 2;
      } else {
        this.side--;
      }
      return false;
    }
    return Bubble.__super__.onTimer.call(this, event);
  };

  Bubble.prototype.isInsideElement = function(mouseX, mouseY) {
    return (mouseX >= (this.x - this.side / 2)) && (mouseX <= (this.x + this.side / 2)) && (mouseY >= (this.y - this.side / 2)) && (mouseY <= (this.y + this.side / 2));
  };

  Bubble.prototype.inCollision = function() {
    var dblDiffX, dblDiffY, dblDistance, dblSquaredX, dblSquaredY, dblSumSide, objElement, _i, _len, _ref;
    _ref = this.objBox.arrElements;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      objElement = _ref[_i];
      if ((objElement != null) && objElement !== this) {
        dblDiffX = objElement.x - this.x;
        dblDiffY = objElement.y - this.y;
        dblSumSide = objElement.side + this.side;
        dblSquaredX = dblDiffX * dblDiffX;
        dblSquaredY = dblDiffY * dblDiffY;
        dblDistance = Math.sqrt(dblSquaredX + dblSquaredY);
        if (dblDistance <= dblSumSide) {
          this.objCollision = objElement;
          return true;
        }
      }
    }
    return false;
  };

  return Bubble;

})(CanvasBoxElement);
