// Generated by CoffeeScript 1.3.3
var CanvasBubbleExample,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Load.CanvasBox();

CanvasBubbleExample = (function(_super) {

  __extends(CanvasBubbleExample, _super);

  function CanvasBubbleExample() {
    return CanvasBubbleExample.__super__.constructor.apply(this, arguments);
  }

  CanvasBubbleExample.prototype.onClick = function(event) {
    var objBubble;
    objBubble = New.Bubble();
    objBubble.x = this.mouseX;
    objBubble.y = this.mouseY;
    this.addElement(objBubble);
    return CanvasBubbleExample.__super__.onClick.apply(this, arguments);
  };

  CanvasBubbleExample.prototype.init = function() {
    var _this = this;
    this.setBackgroundColor("#DDDDFF");
    window.setInterval(function() {
      return _this.loopTimer();
    }, 100);
    return this.play();
  };

  CanvasBubbleExample.prototype.loopTimer = function() {
    var objBubble;
    if (this.arrElements.length > 10) {
      return false;
    }
    if (Math.floor(Math.random() * 10) === 1) {
      objBubble = New.Bubble();
      objBubble.x = Math.floor(Math.random() * this.width);
      objBubble.y = this.height - Math.floor(Math.random() * this.height / 8);
      return this.addElement(objBubble);
    }
  };

  return CanvasBubbleExample;

})(CanvasBox);
